/*
**
** Copyright 2023 Intrinsix
**
** Licensed under the Solderpad Hardware Licence, Version 2.0 (the "License");
** you may not use this file except in compliance with the License.
** You may obtain a copy of the License at
**
**     https://solderpad.org/licenses/
**
** Unless required by applicable law or agreed to in writing, software
** distributed under the License is distributed on an "AS IS" BASIS,
** WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
** See the License for the specific language governing permissions and
** limitations under the License.
**
*******************************************************************************
** CSR access test
** This tests consists of calling the functions generated by gen_csr_test.py
** in the proper privilege modes.
** It also checks that there are no expected exceptions that did not occur.
**
** Recomended method of invoking the gen_csr_test.py script is to run it the same
** directory as this file with the following command line:
**
**  python3 gen_csr_test.py --csr_file ../../../../env/corev-dv/cv32e20_csr_template.yaml
**
*******************************************************************************
*/

#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
#include "custom_handlers.h"
#include "riscv_csr_test_0.h"
#include "cv32e20_dv.h"

volatile int glb_expect_illegal_insn    = 0;
volatile int glb_fail_count             = 0;
volatile int  glb_csr_address = 0;

/* Failure entry point invoked from custom_handlers.S (csr_fail_loop) when an
 * unexpected exception/mismatch occurs.  Signals failure to the testbench. */
void test_fail(void) {
    TEST_FAILED;
    while (1) { }
}

int main(int argc, char *argv[]) {
    interrupt_csr_check();
    machine_mode_check();
    if (glb_expect_illegal_insn != 0) {
      printf ("ERROR: Still expecting %d illegal instruction interrupt(s) at machine mode check.",
	      glb_expect_illegal_insn);
      TEST_FAILED;
    }
    csr_check_unimplemented();
    if (glb_fail_count > 0) {
      printf ("ERROR: Got responses from %d CSR address that are not expected.",
	      glb_fail_count);
      TEST_FAILED;
    }
    if (glb_expect_illegal_insn != 0) {
      printf ("ERROR: Still expecting %d illegal instruction interrupt(s) after checking unimplmented addresses.",
	      glb_expect_illegal_insn);
      TEST_FAILED;
    }
    /* CV32E20 is Machine-mode only (requirement PVL-20): there is no User
     * mode, so the user-mode portion of this generated test
     * (switch_to_user_mode / user_mode_check / switch_to_machine_mode) is
     * omitted.  Only the machine-mode and unimplemented-CSR checks apply. */
    TEST_PASSED;
}
